# Generated by Django 5.0.2 on 2024-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predicting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_File_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Excel_Row_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('issue_key', models.CharField(max_length=100)),
                ('issue_id', models.CharField(max_length=100)),
                ('parent_id', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('project_key', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_url', models.URLField()),
                ('priority', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=255)),
                ('reporter', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('last_viewed', models.DateTimeField()),
                ('resolved', models.DateTimeField()),
                ('affects_versions', models.CharField(max_length=255)),
                ('fix_versions', models.CharField(max_length=255)),
                ('original_estimate', models.DurationField()),
                ('remaining_estimate', models.DurationField()),
                ('time_spent', models.DurationField()),
                ('work_ratio', models.FloatField()),
                ('original_estimate_currency', models.CharField(max_length=10)),
                ('remaining_estimate_currency', models.CharField(max_length=10)),
                ('time_spent_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Uploaded_file_model',
        ),
        migrations.AddField(
            model_name='excel_file_data',
            name='excel_rows',
            field=models.ManyToManyField(to='Predicting_app.excel_row_data'),
        ),
    ]
